version: '3.0'

services:
  nginx:
    container_name: dc_drupal-web
    image: drupal:latest
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      VIRTUAL_HOST: ${DRUPAL_HOSTNAME}
      VIRTUAL_PORT: ${HTTP_PORT:-80}
      LETSENCRYPT_HOST: ${DRUPAL_HOSTNAME}
      LETSENCRYPT_EMAIL: ${DRUPAL_ADMIN_MAIL}
    volumes:
#      - ./data/drupal:/var/www/html:rw
      - ./data/drupal/modules:/var/www/html/modules:rw
      - ./data/drupal/profiles:/var/www/html/profiles:rw
      - ./data/drupal/themes:/var/www/html/themes:rw
      - ./data/drupal/sites:/var/www/html/sites:rw
    restart: always

  drupal-db:
    restart: always
    container_name: dc_drupal-db
    image: wodby/mariadb:10.1-2.3.3
#    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DBROOT}
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${DBUSER}
      MYSQL_PASSWORD: ${DBPASS}
    volumes:
      - ./data/mysql/:/var/lib/mysql
#  postgres:
#    container_name: dc_drupal-db
#    image: postgres:10
#    environment:
#      POSTGRES_PASSWORD: your_postgres_password
#    volumes:
#        - ./data/mysql/:/var/lib/mysql
##        - db_data:/var/lib/postgresql/data
#    restart: always

#volumes:
#  drupal_modules:
#  drupal_profiles:
#  drupal_themes:
#  drupal_sites:
#  db_data:

